name: CD-Liara
on:
  push:
    branches:
      - redesign
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: update-liara
        env:
          LIARA_TOKEN: ${{ secrets.ALI_NAJMABADI_SECRET }}
        run: |
          npm i -g @liara/cli@5
          liara deploy --app="new-docs" --api-token="$LIARA_TOKEN" --no-app-logs